---
- name: Get the remote /proc/cmdline content
  command: cat /proc/cmdline
  register: proc_cmdline

- name: Activating cgroup support for Ubuntu
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
  when:
    - ansible_distribution == 'Ubuntu'
    - ( ansible_facts.architecture is search("arm") or
        ansible_facts.architecture is search("aarch64") )
    - ( proc_cmdline['stdout'].find('cgroup_enable=cpuset') == -1 or
        proc_cmdline['stdout'].find('cgroup_memory=1') == -1 or
        proc_cmdline['stdout'].find('cgroup_enable=memory') == -1 )
